[project]
site_name = "FBG"
site_description = "Documentation for Figure Blockout Generator - a Blender add-on for generating proportioned human blockout figures."
site_author = "Makatopia"
site_url = "https://makatopia.github.io/FBG_Documentation/"
copyright = "Copyright &copy; 2026 Makatopia"

nav = [
  { "Home" = "index.md" },
  { "Installation" = "installation.md" },
  { "Getting Started" = "getting-started.md" },
  { "How FBG Works" = "how-fbg-works.md" },
  { "Proportions" = "proportions.md" },
  { "Display" = "display.md" },
  { "Pose" = [
    "pose/index.md",
    "pose/root.md",
    "pose/shoulders-arms.md",
    "pose/hands.md",
    "pose/torso-head.md",
    "pose/pelvis.md",
    "pose/legs.md",
    "pose/feet.md",
  ]},
  { "Pose Combos" = "pose-combos.md" },
  { "Animation" = "animation.md" },
  { "Baking" = "baking.md" },
]

extra_css = ["assets/stylesheets/extra.css"]
extra_javascript = [
    "assets/javascripts/medium-zoom.js",
    "assets/javascripts/zoom.js"
]

[project.theme]
language = "en"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.expand",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    # "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[project.theme.palette]
scheme = "slate"
